#pragma pack (push,1) 
#pragma pack (1)

#define ST(n) n
#define S_COMPILE_EXPR__CASO__I_NO_CONTEMPLADON "Compile_expr: Caso %i no contempladon"
#define S_CASO_DE_BENEF_NO_CONTEMPLADO          "Caso de benef no contemplado"
#define S_CASO_NO_CONTEMPLADO_                  "Caso no contemplado!"
#define S_W                                     "w"
#define S_TO_DISK__CANNOT_OPEN_FILE__S_         "to_disk: Cannot open file %s."
#define S_TO_DISK__CANNOT_CLOSE_FILE__S_        "to_disk: Cannot close file %s."
#define S_R                                     "r"
#define S_FROM_DISK__CANNOT_OPEN_FILE__S_       "from_disk: Cannot open file %s."
#define S_FROM_DISK__CANNOT_CLOSE_FILE__S_      "from_disk: Cannot close file %s."
#define S_BENEFICIO_NO_CONTEMPLADO_             "Beneficio no contemplado."
#define S_EXPRESION_NO_CONTEMPLADA_PARA_LA_     "Expresion no contemplada para la evaluacion."
#define S_SUMA_MAL_TIPADA                       "SUMA MAL TIPADA"
#define S_RESTA_MAL_TIPADA                      "RESTA MAL TIPADA"
#define S_NEGATIVE_ARITHMETIC_MULTI_SET         "Negative Arithmetic Multi Set"
#define S_DIVISION_BY_ZERO                      "Division by zero"
#define S_EVIN__DAY__                           "EvIN: Day: "
#define S_EVIN__ALGO_NO_CONTEMPLADO_            "EvIN: Algo no contemplado."
#define S_EVCOMPLEMENT__CASO_NO_CONTEMPLADO     "EvCOMPLEMENT: caso no contemplado"
#define S_EVSIZE__CASO_NO_CONTEMPLADO           "EvSIZE: caso no contemplado"
#define S_EVLENGTH__CASO_NO_CONTEMPLADO         "EvLENGTH: caso no contemplado"
#define S_EVBYMEANS___ESTO_NO_DEBERIA_PASAR_    "EvBYMEANS: (esto no deberia pasar)"
#define S_BELONGS__CASO_NO_CONTEMPLADO__        "BELONGS: caso no contemplado: "
#define S_SWITCH_COMMANDO___CASO_NO_CONTEM      "switch(commando)->Caso no contemplado."
#define S_ERROR___S                             "ERROR: %s"
#define S_INTENTO_DE_POPEAR_EXPR_STACK_VACIO    "Intento de popear expr_stack vacio"
#define S_INTENTO_DE_POPEAR_BENEF_STACK_VACIO   "Intento de popear benef_stack vacio"
#define S_INTENTO_DE_POPEAR_PARAM_STACK_VACIO   "Intento de popear param_stack vacio"
#define S_INTENTO_DE_POPEAR_PROMO_STACK_VACIO   "Intento de popear promo_stack vacio"
#define S_INTENTO_DE_SWAPEAR_UNA_PILA_VACIA_    "Intento de swapear una pila vacia."
#define S_INTENTO_DE_SWAPEAR_UNA_PILA_CON_      "Intento de swapear una pila con un solo elemento."
#define S_INTENTO_DE_SWAPEAR_2_UNA_PILA_VACIA_  "Intento de swapear_2 una pila vacia."
#define S_INTENTO_DE_SWAPEAR_2_UNA_PILA1        "Intento de swapear_2 una pila con un solo elemento."
#define S_INTENTO_DE_SWAPEAR_2_UNA_PILA2        "Intento de swapear_2 una pila con solo dos elementos."
#define S_VALSTACK_C__ESTO_NO_DEBERIA_OCURRIR_  "valstack.c: Esto no deberia ocurrir nunca!"
#define S_UNREF_E__CASO_NO_CONTEMPLADO          "unref_e: Caso no contemplado"

#pragma pack (pop) 
