#pragma pack (push,8) 
#ifndef __GUI_PROP_H
#define __GUI_PROP_H

#pragma warning (disable:4786)
#include <string>
using namespace std;

#include "IniEntity.h"

extern IniFile ini_def;
bool CREATE_PROPERTIES(char *path);


enum ALIGNMENT { ALIGNMENT_RIGHT, ALIGNMENT_LEFT, ALIGNMENT_CENTER, ALIGNMENT_TRAILING,
                 ALIGNMENT_LEADING };

int verifyIfFlag( int type );
int verifyPanel( int type );

#define T_DATOS_MEDIO_0_AGREGAR T_MEDIO_0_AGREGAR
#define T_DATOS_MEDIO_0_BORRAR T_MEDIO_0_BORRAR
#define T_DATOS_MEDIO_1_AGREGAR T_MEDIO_1_AGREGAR
#define T_DATOS_MEDIO_1_BORRAR T_MEDIO_1_BORRAR
#define T_DATOS_MEDIO_2_AGREGAR T_MEDIO_2_AGREGAR
#define T_DATOS_MEDIO_2_BORRAR T_MEDIO_2_BORRAR
#define T_DATOS_MEDIO_3_AGREGAR T_MEDIO_3_AGREGAR
#define T_DATOS_MEDIO_3_BORRAR T_MEDIO_3_BORRAR
#define T_DATOS_MEDIO_4_AGREGAR T_MEDIO_4_AGREGAR
#define T_DATOS_MEDIO_4_BORRAR T_MEDIO_4_BORRAR
#define T_DATOS_MEDIO_5_AGREGAR T_MEDIO_5_AGREGAR
#define T_DATOS_MEDIO_5_BORRAR T_MEDIO_5_BORRAR
#define T_DATOS_MEDIO_6_AGREGAR T_MEDIO_6_AGREGAR
#define T_DATOS_MEDIO_6_BORRAR T_MEDIO_6_BORRAR
#define T_DATOS_MEDIO_7_AGREGAR T_MEDIO_7_AGREGAR
#define T_DATOS_MEDIO_7_BORRAR T_MEDIO_7_BORRAR
#define T_DATOS_MEDIO_8_AGREGAR T_MEDIO_8_AGREGAR
#define T_DATOS_MEDIO_8_BORRAR T_MEDIO_8_BORRAR
#define T_DATOS_MEDIO_9_AGREGAR T_MEDIO_9_AGREGAR
#define T_DATOS_MEDIO_9_BORRAR T_MEDIO_9_BORRAR
#define T_DATOS_MEDIO_10_AGREGAR T_MEDIO_10_AGREGAR
#define T_DATOS_MEDIO_10_BORRAR T_MEDIO_10_BORRAR

#endif

#pragma pack (pop) 
