#ifndef _CR1_H
#define _CR1_H
int CR1();
void CR1_LAZO_PRINCIPAL();
void CR1_ACTIVA_ANULACION();
int CR1_EXISTE_ITEM( long cod_especial, int presentacion, char *cod_barra );
void FIN_DE_TICKET(int script);
int CR1_AUTORIZA_ANULACIONES();
void CR1_INFORMES();
void CR1_VALIDA_TARJETA( int mensaje, int medio_tarjeta );
int CR1_CIERRE();
void PETICION_DE_CODIGO( int status );
void SWITCH_PETICION_DE_CODIGO();
void CR1_PETICION_DE_PRESENTACIONES();
void CR1_FACTURA( int nc, int tipo  );
/*float*/ double CR1_PEDIR_PESO();
float CR1_PEDIR_PRECIO();
void CR1_HABILITA_SCANNER(int clave);
void CR1_INICIALIZAR_VAR_TICKET();
int CR1_AUTORIZA_PASAR_LIMITE();
int CR1_ELEGIR_PRESENTACION();
void CR1_ADOPTA_PRESENTACION( int nro, int inicial );
void CR1_CALCULA_RECARGO();
void CR1_CALCULA_IVA( void );
int CR1_BUSCA_CODIGO( int enganche );
int CR1_EJECUTA_FUNCION( int funcion );
int CR1_AGREGA_ITEM( int enganche, char origen, int tipo, char tipo_evento_orig );
void ANULA_ENTRADA();
void AGREGA_ITEM_AL_TICKET( int h, int resta, int enganche, int grabar, char origen );
int CR1_PIDE_CODIGO();
void SETEAR_FUNCION( int funcion, int condicion );
int ES_ENVASE( int h );
void CR1_INTERESES();
void CODIGO_INEXISTENTE();
int INGRESA_CODIGO_BARRAS();
void HABILITAR_PRECIO_CR();
void EVALUAR_CODIGOS_ESPECIALES( int largo_codigo );
int EVALUAR_CODIGOS_BALANZA( char *id_balanza, char *buffer, int largo_codigo );
void CAMBIA_ESPACIO_POR_CERO( char *m );
void ARMA_COD_BARRA( char *cod_barra, double precio );
int CONDICIONES_PARA_CIERRE();
void RECALCULA_ITEM_POR_PRECIO( double importe );
int AGREGAR_ARTICULO( long cod, double importe, char origen, int tipo );
void TECLA_NOVIOS();
int EXENTO_COMO_GRAVADO( int tipo );
void CR1_ABRIR_CAJON();
void REPINTAR_PANEL();
int CR1_ITEM_GRAVADO();
void CR1_PUEDE_ANULAR_LINEA( long cod_especial, int presentacion );
void DESCUENTO_T_CHIP();
int CR1_EXISTE_DESCUENTO_CANTIDAD( long cod_especial, int presentacion );
int BUSCA_ITEM_PROMO();
void CR1_EXENTO_ESPECIAL( int tipo );
void CR1_TICKET_FACTURA( void );
void CR1_INCONSISTENCIA_FISCAL( int sumar );
int CR1_VERIFICAR_LIMITES_FACTURACION( double total, int modo );
void ACTUALIZAR_X( void );
void MODALIDAD_BIEN_DE_USO( void );
void MOSTRAR_MODOA_BIEN_DE_USO_EN_PANTALLA( void );
void CONSULTA_DE_ARTICULO( int muestra_promociones );
char *BUSCA_MENSAJE_STRING( int id );
void MENSAJE_SIN_CMR();
int _ACTUALIZAR_TOTAL_X( int espera_respuesta );
void EVALUAR_COD_TEMPLATE();
void TOMAR_CANTIDAD_SCANNER();
void MOSTRAR_MODO_BIEN_DE_USO_EN_PANTALLA( void );
long GRABAR_CIERRE( void );
int BUSCA_ID_PROMO( int cod_promo );
char *ST( int id );
int CR1_BUSCAR_ITEM_ORIGINAL_POR_DATO_ADICIONAL( int datos_adicionales );
int MOSTRAR_SIN_IVA_ELSALVADOR( void );
void CR1_FACTURA_TIPO( int nc, int tipo );
int CR1_EXISTE_ITEM_DIF_PRECIO( long cod_especial, int presentacion, int anulacion,
                                char *cod_barra );
int CR1_ITEM_DIF_PRECIO( long cod_especial, int presentacion, char *cod_barra );
int CARGAR_MONEDERO_ELECTRONICO( int origen_promo, char *mensaje );
int       VERIFICA_EVENTO_NC_DEV( char tipoEvento );
void      BORRAR_CONTADOR_ARTICULO( );
void	     IMPRIMIR_COPIA_TICKET_FACTURA( );
void      CR1_FRANQUEO( double importe, int modo );
void      CEREAR_DATOS_COMPROB_ANTERIOR( void );
void		CR1_CONTADOR_INIT( );
int      CR1_CONTADOR_ARTICULO( long cod_especial, char *cod_barra, int item );
void      GUARDAR_DATOS_PROD_RESERVADOS( long id_transaccion, char *nro_linea,
double monto, long valor );
int       OBTENER_COD_ESPECIAL_COBRO( int cod_cobro );
int CR1_EXISTE_ITEM_ESTRICTO( long cod_esp, int presentacion, char *cod_barra, int comp_por_importe );
void NOMBRE_MEDIO_SUBMEDIO( int medio, int submedio, char *nombre, int largo );
void PROCESAR_PROMOCIONES_EN_TICKET_EN_ESPERA( void );
void PEDIR_MOTIVO_OPERACION_NEGATIVA( int *cod_solicitud, int motivo );
void VERIFICAR_EVENTOS( void );
int AGREGAR_ARTICULO_GRAVADO( long cod, double importe, int tipo, char origen );
int AGREGAR_ARTICULO_EXENTO( long cod, double importe, int tipo, char origen );
char *ST_MEM( int stringtId, char **var );

#endif
