/*												                                        */
/* ARCHIVOS DE LA TPV 1000 								                         */
/* Versión: AARCH_18_09_2008_0348                                           */
/*								                                                    */
/****************************************************************************/
/* Ej: AARCH_05_10_2007_0345                                                */
/* Nombre del Archivo    = AARCH                                            */
/* Fecha de Modificacion = 05_10_2007                                       */
/* Cantidad de Archivos  =  345                                             */
/****************************************************************************/

#define  CANTIDAD_ARCHIVOS     348

#define _CAB_DAT                 1
#define _CAB_DAT_REMOTO          2
#define _PIE_DAT                 3
#define _PIE_DAT_REMOTO          4
#define _CONFIG_DAT              5
#define _CONFIG_DAT_REMOTO       6
#define _FACTU_MEM               7
#define _FACTU_MEM_REMOTO        8
#define _PROMO_SIC               9
#define _PROMO_SIC_REMOTO       10
#define _PRO_ART_SIC            11
#define _PRO_ART_SIC_REMOTO     12
#define _PRO_DEP_SIC            13
#define _PRO_DEP_SIC_REMOTO     14
#define _PRO_MED_SIC            15
#define _PRO_MED_SIC_REMOTO     16
#define _ARCHIVOS_LOG           17
#define _ARCHIVOS_LOG_REMOTO    18
#define _SISTEMA_LOG            19
#define _SISTEMA_LOG_REMOTO     20
#define _BTRIEVE_LOG            21
#define _BTRIEVE_LOG_REMOTO     22
#define _BANCOS_SIC             23
#define _BANCOS_SIC_REMOTO      24
#define _CAJEROS_SIC            25
#define _CAJEROS_SIC_REMOTO     26
#define _CUO_TAR_SIC            27
#define _CUO_TAR_SIC_REMOTO     28
#define _DPTO_SIC               29
#define _DPTO_SIC_REMOTO        30
#define _T_COMPRA_SIC           31
#define _T_COMPRA_SIC_REMOTO    32
#define _MUTUALES_SIC           33
#define _MUTUALES_SIC_REMOTO    34
#define _COBROS_SIC             35
#define _COBROS_SIC_REMOTO      36
#define _PAGOS1_SIC             37
#define _PAGOS1_SIC_REMOTO      38
#define _PAGOS2_SIC             39
#define _PAGOS2_SIC_REMOTO      40
#define _TER_CAJA_SIC           41
#define _TER_CAJA_SIC_REMOTO    42
#define _CUO_CTA_SIC            43
#define _CUO_CTA_SIC_REMOTO     44
#define _CUO_MUT_SIC            45
#define _CUO_MUT_SIC_REMOTO     46
#define _ARTICULO_SIC           47
#define _ARTICULO_SIC_REMOTO    48
#define _PRESENT_SIC            49
#define _PRESENT_SIC_REMOTO     50
#define _TARJETA_SIC            51
#define _TARJETA_SIC_REMOTO     52
#define _MEDIOS_SIC             53
#define _MEDIOS_SIC_REMOTO      54
#define _IMPUESTO_SIC           55
#define _IMPUESTO_SIC_REMOTO    56
#define _MOV_CTA_SIC            57
#define _CLIENTES_SIC           58
#define _ALTAS_SIC              59
#define _ALTAS_PR_SIC           60
#define _MODIF_SIC              61
#define _MODIF_PR_SIC           62
#define _PEND1_SIC              63
#define _PEND2_SIC              64
#define _REND_CAJ_SIC           65
#define _TRANSAC_SIC            66
#define _SCRIPT_SIC             67
#define _ART_DAT_SIC            68
#define _ACU_VTA_SIC            69
#define _ACU_VTA_ALL            70
#define _ACU_VTA_REMOTO         71
#define _ACU_VTA_REMOTO_BAK     72
#define _ACU_VTA_VENTAS_Z       73
#define _ACU_VTA_BAK            74
#define _FECHA_EVE              75
#define _FECHA_CUP              76
#define _FECHA_VTA              77
#define _CUPON_ZZZ              78
#define _CUPON_BAK              79
#define _CUPON_REMOTO           80
#define _OFF_LINE_ZZZ           81
#define _OFF_LINE_REMOTO        82
#define _OFF_LINE_BAK           83
#define _TARJETAS_ASC           84
#define _CHEQUES_ASC            85
#define _TICKET_ASC             86
#define _MUTUAL_ASC             87
#define _COBROS_ASC             88
#define _COBROS_ASC_BAK         89
#define _COBROS_ASC_REMOTO      90
#define _PAGOS_ASC              91
#define _PAGOS_ASC_BAK          92
#define _PAGOS_ASC_REMOTO       93
#define _TOTALES_ASC            94
#define _CTACTE_ASC             95
#define _DEPARTA_ASC            96
#define _TOTALES_ASC_REMOTO     97
#define _TARJETAS_ASC_REMOTO    98
#define _CHEQUES_ASC_REMOTO     99
#define _CTACTE_ASC_REMOTO     100
#define _DEPARTA_ASC_REMOTO    101
#define _TICKET_ASC_REMOTO     102
#define _MUTUAL_ASC_REMOTO     103
#define _TICKET_BTR            104
#define _E_TICKET_BTR          105
#define _PAGO_BTR              106
#define _VARIOS_BTR            107
#define _EVENTOS_BAK		   108
#define _EV_CONT_BAK           109
#define _PAGO_BAK              110
#define _VARIOS_BAK            111
#define _TICKET_BTR_REMOTO     112
#define _E_TICKET_BTR_REMOTO   113
#define _PAGO_BTR_REMOTO       114
#define _VARIOS_BTR_REMOTO     115
#define _TICKET_ALL            116
#define _E_TICKET_ALL          117
#define _PAGO_ALL              118
#define _VARIOS_ALL            119
#define _TICKET_000            120
#define _E_TICKET_000          121
#define _PAGO_000              122
#define _VARIOS_000            123
#define _ACU_VTA_000           124
#define _CAJAS_SIC             125
#define _CAJAS_SIC_REMOTO      126
#define _AUTOR_DAT             127
#define _ENVIO                 128
#define _RESP                  129
#define _PLU_SIC               130
#define _PLU_SIC_REMOTO        131
#define _RANGOS_SIC            132
#define _RANGOS_SIC_REMOTO     133
#define _CR_EXE                134
#define _CR_EXE_REMOTO         135
#define _CR_INI                136
#define _CR_INI_REMOTO         137
#define _MENSAJES_DAT          138
#define _MENSAJES_DAT_REMOTO   139
//#define _PINPAD_DAT            140
#define _SEND_MON              141
#define _EXPORT                142
#define _IMPORT                143
#define _FLAGS_DAT             144
#define _FLAGS2_DAT            145
#define _STANDBY_DAT           146
#define _PERFILES_SIC          147
#define _ART_PERF_SIC          148
#define _PERF_DES_SIC          149
#define _FUNCION_SIC           150
#define _CLASIF1_SIC           151
#define _CLAS_PER_SIC          152
#define _VIGENCIA_SIC          153
#define _T_FILE_DAT            154
#define _SEND                  155
#define _RECEIVE               156
#define _PRO_CLAS_SIC          157
#define _NODOS_SIC             158
#define _CONCEPTO_SIC          159
#define _CONCEPTO_SIC_REMOTO   160
#define _TMP_TRAN_BTR          161
#define _CLI_AFI_SIC           162
#define _PAR_AFI_MEM           163
#define _EST_AFI_SIC           164
#define _PRO_GRU_SIC           165
#define _ART_BEN_SIC           166
#define _PRO_CLI_SIC           167
#define _NOVIOS_BIN            168
#define _TRANSFER_BIN          169
#define _RETIROS_BIN           170
#define _FONFIJO_BIN           171
#define _CIERRE_BIN            172
#define _PEDIDOS1_BTR          173
#define _PEDIDOS2_BTR          174
#define _TAR_MED_BTR           175
#define _ARTICULO_TMP_SIC      176
#define _TAR_ESP_SIC           177
#define _COBROS_MEDIOS_BTR     178
#define _IVA_SIC               179
#define _VTA_CLAS_SIC          180
#define _VTA_MED_SIC           181
#define _VTA_XYZ_SIC           182
#define _SCRIPT_RTA_SIC        183
#define _CLI_CHEQ_SIC          184
#define _VARIOS_BAK_ULTIMO     185
#define _TICKET_BAK_ULTIMO     186
#define _E_TICKET_BAK_ULTIMO   187
#define _PAGO_BAK_ULTIMO       188
#define _DIF_CAJERO            189
#define _CLIENTES_NOV          190
#define _DIF_TARJ              191
#define _TRANSAC2_SIC          192
#define _EV_CIERRE_BTR         193
#define _EV_CIERRE_BAK         194
#define _EV_CIERRE_000         195
#define _CUO_CMR               196
//#define _***LIBRE1***          197
#define _PAGO_BTR_ENTR         198
#define _TICKET_BTR_ENTR       199
#define _E_TICKET_BTR_ENTR     200
#define _VARIOS_BTR_ENTR       201
#define _CLI_CHEQ_SIC_ENTR     202
#define _FACTU_MEM_ENTR        203
#define _REMITO_MEM            204
#define _REMITO_MEM_ENTR       205
#define _REMITO_MEM_REMOTO     206
#define _HAB_DIFERIMIENTO_TAR  207
#define _EV_T_COMPRA_SIC       208
#define _EV_T_COMPRA_SIC_ENTR  209
#define _EV_COD_BARRA_BAK      210
#define _EV_T_COMPRA_SIC_000   211
#define _TRANSAC_BAK           212
#define _TRANSAC2_000          213
#define _TICKET_HIST_BTR       214
#define _E_TICKET_HIST_BTR     215
#define _PAGO_HIST_BTR         216
#define _EV_T_COMPRA_HIST_SIC  217
#define _EV_CIERRE_HIST_BTR    218
#define _TRANSAC2_BAK          219
#define _TARJ_DAT              220
#define _TEMPLATE_SIC          221
#define _BOLETIN_SIC           222
#define _BOLETIN_NOV           223
#define _CTRL_CAJERO           224
#define _JOURNAL_DAT           225
#define _JOURNAL_BAK           226
#define _PRO_FID_SIC           227
#define _MOTIVO_SIC            228
#define _EV_DPAGO_BTR          229
#define _EV_DPAGO_HIST_BTR     230
#define _EV_DPAGO_BTR_ENTR     231
#define _EV_DMEDIOS_BAK        232
#define _EV_DPAGO_BTR_000      233
#define _DMEDIOS_SIC           234
#define _EV_SUPER_BTR          235
#define _EV_SUPER_HIST_BTR     236
#define _EV_SUPER_BTR_ENTR     237
#define _EV_SUPER_BAK          238
#define _EV_SUPER_BTR_000      239
#define _OLMEDIOS_SIC          240
#define _CTRL_NC_BTR           241
#define _T_EVENTOS_SIC         242
#define _COPIAS_T_SIC          243
#define _INSTIT                244
#define _BOL_CHQ_BTR           245
#define _TRANS_BAL_CAB         246
#define _TRANS_BAL_DET         247
#define _DEV_ENV_SIC           248
#define _AUX_ENV_SIC           249
#define _BANDAS_SIC            250
#define _BANDAS_ART_SIC        251
#define _BANDAS_CLAS_SIC       252
#define _RTA_SWITCH_BTR        253
#define _COB_MED_SIC           254
#define _E_DES_PRO_BTR         255
#define _E_DES_PRO_BAK         256
#define _E_DES_PRO_BTR_REMOTO  257
#define _E_DES_PRO_HIST        258
#define _E_DES_PRO_000         259
#define _CUO_MED_SIC           260
#define _CUO_MED_SIC_REMOTO    261
#define _EV_FACTU_BTR          262
#define _EV_FACTU_000          263
#define _EV_FACTU_BAK          264
#define _EV_FACTU_HIS          265
#define _EV_FACTU_ENTR         266
#define _BOLETIN_TMP           267
#define _TKT_TMP_SIC           268
#define _PRO_PLU_SIC           269
#define _CAMB_VAL_HAB_SIC      270
#define _BOL_TIC_TMP           271
#define _TAR_TR2_SIC           272
#define _CUO_GRU_SIC           273
#define _TENVASE_SIC           274
#define _GRUPO_ENV_SIC         275
#define _E_DES_PRO_BTR_ENTR    276
#define _TOMRA_TMP             277
#define _CATEGORIA_IMPUESTO    278
#define _MOTIVO_EXENTO_SIC     279
#define _GRUPOART_SIC          280
#define _GRUPOCLA_SIC          281
#define _EXCL_MED_SIC          282
#define _PEDIDO_PIN_TMP        283
#define _SETCONFIG             284
#define _LOGCONF               285
#define _PROMO_A_SIC           286
#define _VENDEDOR_LOCAL        287
#define _CLIENTES_TMP_SIC      288
#define _EV_ENVASES_BTR        289
#define _EV_ENVASES_000        290
#define _EV_ENVASES_BAK        291
#define _EV_ENVASES_ENTR       292
#define _EV_ENVASES_HIS        293
#define _FORM_DGR_SIC          294
#define _PREMIOS               295
#define _TIPO_PREMIOS          296
#define _PREM_ENT              297
#define _EV_B_PROMO_BTR        298
#define _EV_B_PROMO_000        299
#define _EV_B_PROM_BAK_ULTIMO  300
#define _EV_B_PROMO_HIST_BTR   301
#define _EV_B_PROMO_ALL        302
#define _EV_B_PROMO_BTR_ENTR   303
#define _EV_B_PROM_BTR_REMOTO  304
#define _EV_B_PROMO_BAK        305
#define _NRO_CLI               306
#define _GRUPOCLI              307
#define _DOSIFICACION          308
#define _D_ENTRY_SIC           309
#define _COND_IVA_SIC          310
#define _KEY_POS_DAT           311
#define _TIPO_DOC_SIC          312
#define _TIPO_EVENTO_SIC       313
#define _OP_CLI_SIC            314
#define _MASCARA_BTR           315
#define _CLICOBRO_BTR          316
#define _DET_OPER_SIC          317
#define _TIP_MOV_BTR           318
#define _MOTIVO2               319
#define _MEDIOS_P_REINTEGROS   320
#define _ALTA_OP_CLI           321
#define _MODIF_OP_CLI          322
#define _CAJA_SUC_SIC          323
#define _CIERRE_DE_LOTE_TARJ   324
#define _TIP_MOV_CAJA          325
#define _INFORME_SUP_SIC       326
#define _COMTAR                327
#define _SUCURSALES_SIC        328
#define _TICKET_BAK2           329
#define _E_TICKET_BAK2         330
#define _PAGO_BAK2             331
#define _VARIOS_BAK2           332
#define _EV_CIERRE_BAK2        333
#define _E_DES_PRO_BAK2        334
#define _EV_FACTU_BAK2         335
#define _EV_T_COMPRA_BAK2      336
#define _EV_DPAGO_BAK2         337
#define _EV_SUPER_BAK2         338
#define _OPER_CLI_NOV          339
#define _COB_TAR               340
#define _VUELTOS               341
#define _GARANTIA              342
#define _LIN_MENS_TMP          343
#define _TICK_TMP_BTR          344
#define _D_F_FIJO_SIC          345
#define _TRAN_CRP_SIC          346
#define _TRAN_CRP_000          347
#define _TRAN_CRP_BAK          348
