#ifndef MODO_EJE_H
#define MODO_EJE_H
void TESTEAR_MODO_EJECUCION();
int TESTEAR_CONTINUA_MODO_ENTRENAMIENTO();
void SETEAR_MODO_EJECUCION( int modo );
void MOSTRAR_MODO_ENTRENAMIENTO_EN_PANTALLA( int cajero_operando );
int GRABAR_RNV_EN_ARCHIVO( char *filename );
int SET_ENTRENAMIENTO_OFF();
int SET_ENTRENAMIENTO_ON();
#endif
