#ifndef NC_H
#define NC_H
void PANTALLA_IMPORTAR_NC();
int PIDE_DATOS_IMPORTAR_NC();
int PRECIO_TICKET_ORIGINAL();
int TIPOS_NC();
int REFERENCIA_NC();
int PIDE_TIPO_COMPROBANTE_EN_NC();
int PEDIR_PRECIO_NOTA_CR_LIBRE();
int VERIFICA_NC_AUTORIZADAS();
#endif
