#ifndef RECUP_H
#define RECUP_H
void CRR_INICIALIZAR_RAM_NOVOL();
void CRR_INICIALIZAR_VAR_TICKET_RAM_NOVOL();
void CRR_RECUPERA_POSICION_ARCHIVOS();
int INIT_VARIABLES_ESPEJADAS();
void GRABAR_TICKET( int h );
void RECUPERAR_TICKET();
void CEREAR_VARIABLES_RNV_TICKET();
#endif
