#pragma pack (push,1) 
/* ------------------------------------------------------------------------------
 * Sistema: TPV 1000 - IV
 * Definiciones para la configuraci¢n de comprobantes
 * ------------------------------------------------------------------------------
 */

/*-------------------------- CAMPOS -------------------------*/
#define _LETRA_FACTURA               0x0001
#define _TIPO_COMPROBANTE            0x0002
#define _NUMERO_COMPROBANTE          0x0003
#define _NRO_ORDEN_COMPROBANTE       0x0004
#define _FECHA                       0x0005
#define _HORATKT                     0x0006
#define _NOMBRE_SUCURSAL             0x0007
#define _NOMBRE_CLIENTE              0x0008
#define _DOMICILIO_CLIENTE           0x0009
#define _LOCALIDAD_CLIENTE           0x000a
#define _PROVINCIA_CLIENTE           0x000b
#define _TIPO_IVA_CLIENTE            0x000c
#define _CUIT_CLIENTE                0x000d
#define _CONDICION_VENTA             0x000e
#define _CODIGO_BARRA_12             0x000f
#define _CODIGO_BARRA                0x0010
#define _CODIGO_ARTICULO             0x0011
#define _DESC_ARTICULO               0x0012
#define _IVA_ARTICULO                0x0013
#define _PRECIO_ARTICULO             0x0014
#define _IMPORTE_ARTICULO            0x0015
#define _SUBTOTAL                    0x0016
#define _NETO_GRAVADO                0x0017
#define _EXENTO                      0x0018
#define _IVA1                        0x0019
#define _IVA2                        0x001a
#define _TOTAL                       0x001b
#define _LUGAR_DE_EMISION            0x001c
#define _CANTIDAD_ARTICULO           0x001d
#define _CONTENIDO_ARTICULO          0x001e
#define _UNIDAD_ARTICULO             0x001f
#define _IMPUESTO_INTERNO            0x0020
#define _NUMERO_CLIENTE              0x0021
#define _CANTIDAD_SIN_DECIMALES      0x0022
#define _TASA_IVA1                   0x0023
#define _TASA_IVA2                   0x0024
#define _ILA                         0x0025
#define _IHA                         0x0026
#define _GIRO_CLIENTE                0x0027
#define _OC_GD_CLIENTE               0x0028
#define _CANTIDAD_PRESENTACION       0x0029
#define _CODIGO_PRESENTACION         0x002a
#define _SUC_REMITO_A_FACTURAR       0x002b
#define _NRO_REMITO_A_FACTURAR       0x002c
#define _PRECIO_FINAL                0x002d
#define _NRO_VENDEDOR                0x002e
#define _NUMERO_CAJA                 0x002f
#define _NUMERO_CAJERO               0x0030
#define _RETENCION_DGR               0x0031
#define _PERCEPCION_DGI              0x0032
#define _NRO_BOLETA_ANTERIOR         0x0033
#define _NRO_EVENTO                  0x0034
#define _NUMERO_TARJETA              0x0035
#define _MENSAJE_TARJETA             0x0036
#define _VIGENCIA_TARJETA            0x0037
#define _PRIMER_VTO_TARJETA          0x0038
#define _CANT_CUOTAS_TARJETA         0x0039
#define _VALIDACION_TARJETA          0x003a
#define _NC_DATOS_CAJA               0x003b
#define _NC_DATOS_SUCURSAL           0x003c
#define _NC_DATOS_COMPROBANTE        0x003d
#define _NC_DATOS_FECHA              0x003e
#define _NC_DATOS_TIPO_COMP          0x003f
#define _PERCEP_212_IVA1             0x0040
#define _PERCEP_212_IVA2             0x0041
#define _NRO_TICKET                  0x0042
#define _MARCA                       0x0043
#define _NOMBRE_CAJERO               0x0044
#define _SECUENCIA                   0x0045
#define _NUMERO_Z                    0x0046
#define _NOMBRE_MEDIO                0x0047
#define _BASE_IMPONIBLE              0x0048
#define _COD_IVA                     0x0049
#define _BULTOS                      0x004a
#define _EAN_CLIENTE_AFINIDAD        0x004b
#define _TRANSACCION                 0x004c
#define _CAJA_ANTERIOR               0x004d
#define _FECHA_ANTERIOR              0x004e
#define _TKT_PUNTAJE_VENTA           0x004f
#define _TKT_NUMERO_CLIENTE_AFINIDAD 0x0050
#define _TKT_PUNTAJE_VENTA_TRUNCADO  0x0051
#define _TKT_NOMBRE_CLIENTE_AFINIDAD 0x0052
#define _TKT_FECHA_ACTUALIZACION     0x0053
#define _TKT_PUNTAJE_ACUMULADO       0x0054
#define _TKT_DIFERENCIA_AFINIDAD     0x0055
#define _TKT_CANT_ARTICULOS_AFINIDAD 0x0056
#define _TKT_NUMERO_DOCUMENTO        0x0057
#define _TKT_COTIZACION              0x0058
#define _TKT_IMPORTE_DONACION        0x0059
#define _TKT_NRO_SERIE               0x005a
#define _TKT_PUNTOS_CLIENTE          0x005b
#define _TKT_BUSCA_CLIENTE           0x005c
#define _TKT_DISCRIMINACION_IVA      0x005d
#define _ANIO_CUATRO_DIGITOS         0x005e
#define _FECHA_CUATRO_DIGITOS        0x005f
#define _TOTAL_IMPUESTO_FACTURA      0x0060
#define _TKT_TOTAL_PROMOCION         0x0061
#define _TKT_SI_TOTAL_PROMOCION      0x0062
#define _TKT_BEGIN                   0x0063
#define _TKT_END                     0x0064
#define _TKT_INICIO_CUERPO_SUBTOTAL  0x0065
#define _TKT_FIN_CUERPO_SUBTOTAL     0x0066
#define _COD_CLIENTE_GENERICO        0x0067
#define _DNI_CLIENTE                 0x0068
#define _TKT_CANTIDAD_TOTAL_TMP      0x0069
#define _TKT_IMPORTE_TMP             0x006a
#define _TKT_CANTIDAD_TMP            0x006b
#define _TKT_DESCRIPCION_TMP         0x006c
#define _TKT_WHILE_TMP               0x006d
#define _TKT_END_WHILE_TMP           0x006e
#define _NRI_CLIENTE                 0x006f
#define _DATO_SUBMEDIO_TAR           0x0070
#define _TKT_TOTAL_IMPUESTOS         0x0071
#define _TKT_LETRA_IMPUESTO			 0x0072
#define _NRO_AUTO_TARJETA            0x0073
//SIN_LOTE_TARJETA
//#define _DATO_LOTE_TAR               0x0072
#define _TKT_IMPORTE_INGRESADO       0x0074
#define _TKT_SALDO_TARJETA           0x0075
#define _TKT_MES_ANIO_VENCIMIENTO    0x0076
#define _TKT_DETALLE_SUBMEDIOS       0x0077
#define _TKT_CODIGO_BARRA_COBROS     0x0078
#define _TKT_CODIGO_BARRA_ARTICULO_COBROS     0x0079
#define _TKT_LETRA_NEGRITA                    0x007a
#define _TKT_DESHABILITAR_FORMATOS_LETRAS     0x007b
#define _NC_DATOS_AUTORIZACION       0x007c
#define _TKT_COD_AUTORIZACION		 0x007d
#define _TICKET_FINAL				 0x007e
#define _TRANSACCION_FINAL           0x007f
#define _SECUENCIA_ANTERIOR          0x0080
#define _NUMERO_DE_X				 0x0081
#define _TIPO_TARJETA				 0x0082 
#define _CLIENTE					 0x0083 
#define _VENCIMIENTO				 0x0084 
#define _NUMERO_ESTABLECIMIENTO		 0x0085 
#define _NUMERO_CUPON				 0x0086 
#define _COMPROBANTE_NUMERO			 0x0087 
#define _CODIGO_AUTORIZACION		 0x0088
#define _OPERACION				 	 0x0089
#define _IMPORTE_TARJETA			 0x008a
#define _NUMERO_CUOTAS				 0x008b 
#define _MONEDA						 0x008c
#define _NUMERO_TERMINAL			 0x008d 
#define _NUMERO_LOTE				 0x008e
#define _NUMERO_TPV					 0x008f
#define _NUMERO_SUCURSAL			 0x0090
#define _OPERADOR					 0x0091
#define _TIQUE_REFERENCIA			 0x0092
#define _FIRMA						 0x0093
#define _ACLARACION					 0x0094
#define _PHONE  					 0x0095
#define _IMPRIME_VOUCHER_FISCAL		 0x0096 
#define _ABRIR_DOC_NO_FISCAL		 0x0097 
#define _CERRAR_DOC_NO_FISCAL		 0x0098
#define _SUPERVISOR					 0x0099
#define _NOMBRE_SUPERVISOR			 0x009a

#define _FIN_CAMPOS                  0x0500


//
/*----------------------- FUNCIONES --------------------------*/
#define _LARGO_FACTURA                             0x0501
#define _RENGLONES_CUERPO                          0x0502
#define _POSICION                                  0x0503
#define _POS_X                                     0x0504
#define _POS_Y                                     0x0505
#define _EJECT                                     0x0506
#define _CADENA                                    0x0507
#define _COMIENZO_CUERPO                           0x0508
#define _FIN_CUERPO                                0x0509
#define _LETRA_NORMAL                              0x050a
#define _LETRA_DOBLE_ANCHO                         0x050b
#define _TKT_FIN_INICIALIZACION                    0x050c
#define _INDEPENDIENTES                            0x050d
#define _CADENA_CONTINUA_EN_PROXIMA                0x050e
#define _AGREGAR_IVA_NO_INSCRIPTO                  0x050f
#define _SI_FACTURA_A                              0x0510
#define _CADENA_REEMPLAZO_TICKET                   0x0511
#define _SI_FACTURA_B                              0x0512
#define _LARGO_FACTURA_A                           0x0513
#define _LARGO_FACTURA_B                           0x0514
#define _RENGLONES_CUERPO_A                        0x0515
#define _RENGLONES_CUERPO_B                        0x0516
#define _LARGO_CADENA                              0x0517
#define _TOTAL_EN_LETRAS                           0x0518
#define _REIMPRESION_COMPROBANTE                   0x0519
#define _TOTAL_IMPUESTO                            0x051a
#define _LARGO_REMITO                              0x051b
#define _COMIENZO_CUERPO_FAC_REM                   0x051c
#define _TOTAL_HOJAS_COMPROBANTE                   0x051d
#define _HOJA_ACTUAL                               0x051e
#define _PEDIR_FORMULARIO_CON_TECLA                0x051f
#define _NETO_GRAVADO_COD                          0x0520
#define _IVA1_COD                                  0x0521
#define _IVA2_COD                                  0x0522
#define _SI_NOTA_CREDITO                           0x0523
#define _SI_BIEN_DE_USO                            0x0524
#define _COMIENZO_CUERPO_CANTIDAD                  0x0525
#define _FIN_CUERPO_CANTIDAD                       0x0526
#define _COMIENZO_CUERPO_UNITARIO                  0x0527
#define _FIN_CUERPO_UNITARIO                       0x0528
#define _PRECIO_UNITARIO                           0x0529
#define _PRECIO_TOTAL                              0x052a
#define _TOTAL_TICKET                              0x052b
#define _VUELTO                                    0x052c
#define _CORTE_TICKET                              0x052d
#define _COMIENZO_CUERPO_TOTAL                     0x052e
#define _FIN_CUERPO_TOTAL                          0x052f
#define _COMIENZO_CUERPO_MEDIOS                    0x0530
#define _FIN_CUERPO_MEDIOS                         0x0531
#define _COMIENZO_CUERPO_IVA                       0x0532
#define _FIN_CUERPO_IVA                            0x0533
#define _IMPORTE_MEDIO                             0x0534
#define _SELECT                                    0x0535
#define _COMIENZO_PIE                              0x0536
#define _FIN_PIE                                   0x0537
#define _COMIENZO_CUERPO_VUELTO                    0x0538
#define _FIN_CUERPO_VUELTO                         0x0539
#define _FIN_PARTE_FIJA                            0x053a
#define _COMIENZO_CUERPO_AFINIDAD                  0x053b
#define _FIN_CUERPO_AFINIDAD                       0x053c
#define _SI_MODO_ENTRENAMIENTO                     0x053d
#define _SI_REIMPRESION                            0x053e
#define _SI_ANULACION                              0x053f
#define _SI_MODO_INVENTARIO                        0x0540
#define _SI_DEVOLUCION                             0x0541
#define _COMIENZO_CUERPO_NO_AFINIDAD               0x0542
#define _FIN_CUERPO_NO_AFINIDAD                    0x0543
#define _SI_MEDIO                                  0x0544
#define _TKT_IMPORTE_MEDIO_ME                      0x0545
#define _COMIENZO_CUERPO_DONACION                  0x0546
#define _FIN_CUERPO_DONACION                       0x0547
#define _TKT_DATO_MEDIO                            0x0548
#define _TKT_PRECIO_SIN_IVA_EN_TICKET              0x0549
#define _TKT_SI_VALOR_VARIABLE_RNV                 0x054a
#define _TKT_SI_NO_VALOR_VARIABLE_RNV              0x054b
#define _COMIENZO_CUERPO_ID_CON_CLIENTE            0x054c
#define _FIN_CUERPO_ID_CON_CLIENTE                 0x054d
#define _COMIENZO_CUERPO_ID_SIN_CLIENTE            0x054e
#define _FIN_CUERPO_ID_SIN_CLIENTE                 0x054f
#define _OFFSET_CADENA                             0x0550
#define _TKT_VARIABLE_RNV                          0x0551
#define _TKT_SLIP_ON                               0x0552
#define _TKT_SLIP_OFF                              0x0553
#define _CABECERA_FISCAL                           0x0554
#define _CABECERA_FISCAL_2                         0x0555
#define _PIE_FISCAL                                0x0556
#define _PIE_FISCAL_2                              0x0557
#define _CADENA_FISCAL                             0x0558
#define _ITEM_FISCAL                               0x0559
#define _CADENA_NO_FISCAL                          0x055a
//#define _FISCAL_X                                  0x055b
#define _TKT_COMIENZO_CUERPO_F_FIJO                0x055b
#define _FISCAL_Z                                  0x055c
#define _TKT_FIN_CUERPO_F_FIJO                     0x055d
/*#define _TKT_INICIO_COMANDO_X                      0x055f
#define _TKT_FIN_COMANDO_X                         0x0560
#define _TKT_INICIO_COMANDO_Z                      0x0561
#define _TKT_FIN_COMANDO_Z                         0x0562
#define _TKT_INICIO_IMPRESORA_FISCAL               0x0563
#define _TKT_FIN_IMPRESORA_FISCAL                  0x0564
#define _TKT_INICIO_COMANDO_Y                      0x0565
#define _TKT_FIN_COMANDO_Y                         0x0566
#define _TKT_INICIO_COMANDO_B                      0x0567*/
//#define _TKT_FIN_COMANDO_B                         0x0568
/*#define _TKT_INICIO_COMANDO_T                      0x0569
#define _TKT_FIN_COMANDO_T                         0x056a*/
#define _TKT_INICIO_INF_DIFERENCIA                 0x055e
#define _TKT_FIN_INF_DIFERENCIA                    0x055f
#define _TKT_COMANDO_FISCAL                        0x0560
#define _TKT_LF_RECEIPT                            0x0561
#define _TKT_MAX_LIN_COMENTARIOS                   0x0562
#define _TKT_CARACTERES_X_LIN                      0x0563
#define _TKT_INICIO_CORTE_PAPEL                    0x0564
#define _TKT_FIN_CORTE_PAPEL                       0x0565
#define _TKT_RESET                                 0x0566
//#define _TKT_SI_CONSULTA_TABLA                     0x0574
#define _TKT_TICKS_B                               0x0567
#define _NRO_DOC_FISCAL_COMP                       0x0568
#define _TKT_DATO_ARTICULO                         0x0569
#define _SI_DATO_ARTICULO                          0x056a
#define _MAXIMO_RENGLONES_TRANSFERENCIA            0x056b
#define _TKT_OFFSET_COLUMNA                        0x056c
#define _TKT_NRO_TICKET                            0x056d
#define _TKT_TOTAL                                 0x056e
#define _TKT_NRO_CAJA                              0x056f
#define _TKT_PAUSA                                 0x0570
#define _TKT_FORMULA                               0x0571
#define _TKT_SI_FORMULA                            0x0572
#define _TKT_FOR                                   0x0573
#define _TKT_END_FOR                               0x0574
#define _TKT_LF                                    0x0575
#define _SI_EXENTO                                 0x0576
#define _SI_GRAVADO                                0x0577
#define _COMIENZO_INFORME_00                       0x0578
#define _FIN_INFORME_00                            0x0579
#define _TKT_OFF_VARIABLE_RNV                      0x057a
#define _TKT_SI_VALOR_VARIABLE_RNV_OFF             0x057b
#define _TKT_SI_NO_VALOR_VARIABLE_RNV_OFF          0x057c
#define _TKT_DESC_MEDIO                            0x057d
#define _TKT_TOTALIZAR_TMP                         0x057e
#define _TKT_SI_VALOR_VARIABLE_RNV_Y_SI_MEDIO      0x057f
#define _TKT_SI_NO_VALOR_VARIABLE_RNV_Y_SI_MEDIO   0x0580
#define _PROCESAR_DATOS_ADICIONALES                0x0581
#define _DATO_ADICIONAL_MEDIO_PAGO                 0x0582
#define _DATOS_ADICIONALES_COMPROB                 0x0583
#define _CONFIRMAR_IMPRESION                       0x0584
#define _TKT_CONSULTA_TABLA                        0x0585
#define _COMIENZO_CUERPO_TARJETAS                  0x0586
#define _FIN_CUERPO_TARJETAS                       0x0587
#define _ENVIAR_BMP                                0x0588
#define _COMIENZO_TIMBRADORA                       0x0589
#define _FIN_TIMBRADORA                            0x058a
#define _SET_FONT                                  0x058b
#define _INICIO_INF_SUP                            0x058c
#define _FIN_INF_SUP                               0x058d
#define _INICIO_CAB_INF_SUP                        0x058e
#define _FIN_CAB_INF_SUP                           0x058f
#define _COMIENZO_SI                               0x0590
#define _FIN_SI                                    0x0591
#define _TKT_VERSION                               0x0592
#define _TKT_FECHA_ALINEADA                        0x0593
#define _COMIENZO_PAGO_REINTEGRO                   0x0594
#define _FIN_PAGO_REINTEGRO                        0x0595
#define _COMIENZO_TIMBRADO_REINTEGRO               0x0596
#define _FIN_TIMBRADO_REINTEGRO                    0x0597
#define _TKT_ULTIMO_ID                             0x0598
#define _TKT_CONSULTA_TABLA_SQL                    0x0599
#define _TKT_INICIO_INF_DIFERENCIA_SUBMEDIOS       0x059a
#define _TKT_FIN_INF_DIFERENCIA_SUBMEDIOS          0x059b
#define _INICIO_CAB_INF_DIF_SUB	                   0x059c
#define _FIN_CAB_INF_DIF_SUB                       0x059d
#define _TKT_CANT_EVENTOS                          0x059e
#define _TKT_ID_EVENTO_NRO	                       0x059f
#define _TKT_SI_VALOR_MED						   0x05a0
#define _TKT_DATO_MEDIO_SUBMEDIO				   0x05a1	
#define _TKT_CODIGO_BARRA_FOLIO  				   0x05a2
#define _IMAGEN     							   0x05a3
#define _COMIENZO_DESCRIPCION_CUERPO     		   0x05a4
#define _FIN_DESCRIPCION_CUERPO                    0x05a5
#define _COMIENZO_DESCRIPCION_TARJETA     		   0x05a6
#define _FIN_DESCRIPCION_TARJETA                   0x05a7
#define _TKT_CODIGO_FOLIO                          0x05a8
#define _COMIENZO_IMPORTE_TOTAL                    0x05a9
#define _FIN_IMPORTE_TOTAL                         0x05aa
#define _TKT_COMIENZO_FRANQUEO                     0x05ab
#define _TKT_FIN_FRANQUEO                          0x05ac
#define _TKT_MENSAJE_ESPECIAL					   0x05ad
#define _TKT_ESPERAR_ENTER                         0x05ae
#define _TKT_COMIENZO_TICKET_ESPERA                0x05af
#define _TKT_FIN_TICKET_ESPERA                     0x05b0
#define _TKT_IMPORTE_TOTAL_TMP                     0x05b1
#define _TKT_COMIENZO_INFCOMPARATIVA               0x05b2
#define _TKT_FIN_INFCOMPARATIVA                    0x05b3
#define _COMIENZO_FIN_TICKET                       0x05b4
#define _FIN_TICKET                                0x05b5
#define _TKT_COMIENZO_FRANQUEO_COBROS              0x05b6
#define _TKT_FIN_FRANQUEO_COBROS                   0x05b7
#define _TKT_INTERLINEADO                          0x05b8
#define _TKT_CARACTERES_LINEA                      0x05b9
#define _TKT_REPETIR_CADENA                        0x05ba
#define _NO_DEVOLUCION                      	   0x05bb 
#define _SI_CIERRE_Z							   0x05bc 
#define _SI_CIERRE_X						       0x05bd 
#define _FIN_CIERRE_Z							   0x05be
#define _FIN_CIERRE_X							   0x05bf
#define _COMIENZO_DUPLICADO_TARJETA     		   0x05c0
#define _FIN_DUPLICADO_TARJETA              	   0x05c1
#define _IMPORTE_MEDIO_FF						   0x05c2 
#define _COMIENZO_CUERPO_RETIRO				       0x05c3 
#define _FIN_CUERPO_RETIRO						   0x05c4 
#define _TKT_IMPORTE_DE_RETIROS					   0x05c5 
#define _TKT_TOTAL_DE_RETIROS					   0x05c6 
#define _TOTAL_FF								   0x05c7 
#define _SI_MEDIO_SALIENTE						   0x05c8 
#define _COMIENZO_CUERPO_ING_CAJERO				   0x05c9 
#define _FIN_CUERPO_ING_CAJERO					   0x05ca
#define _LETRA_RESALTADA						   0x05cb 
#define _LETRA_DOBLE_ALTO						   0x05cc 
#define _LETRA_DOBLE_ALTO_NEGRITA		    	   0x05cd 
#define _LETRA_DOBLE_ANCHO_NEGRITA	        	   0x05ce 
#define _LETRA_DOBLE_ANCHO_ALTO				       0x05cf 
#define _LETRA_DOBLE_ANCHO_ALTO_NEGRITA		       0x05d0 //Seba
#define _LETRA_SUBRAYADO						   0x05d1 //Seba 
#define _LETRA_SUBRAYADO_NEGRITA	               0x05d2 //Seba
#define _CAMPOS_CLIENTES                           0x05d3
#define _CANT_DATOS_SOLICITAR                      0x05d4
#define _COMIENZO_CONFIG_DATOS_CLIENTE             0x05d5
#define _FIN_CONFIG_DATOS_CLIENTE                  0x05d6
#define _TKT_FRANQUE0_AL_FINAL                     0x05d7
#define _TKT_COMIENZO_INFO_Y					   0x05d8
#define _TKT_FIN_INFO_Y							   0x05d9
#define _TKT_CAMPO_ARCH_REC						   0x05da
#define _TKT_VALIDACION                            0x05db
#define _TKT_FOR_CONTADOR						   0x05dc
#define _TKT_VALIDACION_AL_FINAL				   0x05dd
#define _COMIENZO_INFORME_05                       0x05de
#define _FIN_INFORME_05                            0x05df
#define _COMIENZO_CABECERA_INFORME_10              0x05e0
#define _FIN_CABECERA_INFORME_10                   0x05e1
#define _TKT_PRODUCTIVIDAD_CAJERO                  0x05e2
//esta declarado VENTA POR DEPARTAMENTO  pero no encuentro el define corresp.
#define _COMIENZO_INFORME_10                       0x05e4
#define _FIN_INFORME_10                            0x05e5
#define _COMIENZO_CABECERA_INFORME_15              0x05e6
#define _FIN_CABECERA_INFORME_15                   0x05e7
#define _COMIENZO_INFORME_15                       0x05e8
#define _FIN_INFORME_15                            0x05e9
#define _TKT_DIA_OPERATIVO			               0x05ea
#define _COMIENZO_CUERPO_RETIRO_CIERRE			   0x05eb 
#define _FIN_CUERPO_RETIRO_CIERRE				   0x05ec 
#define	_LINEA_DE_DESCRIPCION					   0x05ed
#define	_IMPRIME_LINEA_DE_DESCRIPCION			   0x05ee
#define	_PREFERENCIA_IMPRESION					   0x05ef






#define _FIN                                       0xffff

/*--------------------------- Funciones --------------------------*/
void COMP_ajustar_largo( char *cadena );
extern int COMP_evaluar_condiciones( int codigo );
int       CARGAR_CONF_FACTURA(  );
int       CARGAR_CONF_REMITO(  );
long      _tomar_long( char **cadena );
int       _tomar_fecha( char **cadena );
float     _tomar_float( char **cadena );
int       _tomar_entero( char **cadena );
int       CARGAR_CONFIG_TKT( char *nom_arch, /*unsigned char*/struct _ConfTkt *config[], int largo );
void      TRANSFORMAR_CADENA_HEXA( char *cadena, int largo );
void      _tomar_cadena( char **cadena );
int       CARGAR_CONF_TKT(  );
void		 LIBERA_UTI_COMP(  );
void		 _tomar_cadena_dos( char **cadena, char **cobtenida );
#pragma pack (pop) 
